### ISSUE TITLE
Correct place to install when using anaconda

### ISSUE THREAD

**Issue by Bernalms** [DIG-Kaust/conda_envs#1]
Hello professor,

I followed all the steps you synthesized in your script by following the instructions on the PyCurveLab repo, but I am actually planning to reinstall pyct and pyctlops using your script instead. Is this meant to be used with a site specific OS config? i.e. would this be suitable as a shortcut to install Curvelab and the PyCurveLab wrapper?
I am using Anaconda on iOS, 12. I placed packages under /usr/local but I see that anaconda has a location where pyct and pyctlops get installed when using pip, namely:
/users/"my_user"/opt/anaconda3/lib/python3.8/site-packages/pyct

I have found two errors ATM: 
When importing conda complains that the package fdct2_wrapper.py does not exist (and it is true that this file does not existat least under .../python3.8/site-packages/pyct ...)
So I tried renaming fdct2.py and the error stopped but then now I have yet another issue:
NameError: name 'fdct_init' is not defined (hence telling i probably messed up class functions target name when I renamed fdct2_wrapper.py).

there is one single constant. All of this happens inside fdct2.py.
I am wondering if:
1.- the the directory of my curvelab and FFTW is ok to be /usr/local/, or should i install somewhere else?
2.- the installation maybe should be done having fftw, curvelab and PyCt living under the same directory under anacondas package directory:
/users/"my_user"/opt/anaconda3/lib/python3.8/site-packages/

thanks,
Bernal

**Comment by mrava87** [comment]
Hi @Bernalms,
thanks for the issue.

To be honest I tried to install this on my MacOS once but I run into lots of troubles and never looked into it again (if I recall correctly they were similar to what you mention). Everything works fine in Linux, which I think is the OS of choice when doing scientific computing. 

I am not saying you will never succeed on MacOS but it may be a lot of extra work. Have you got access to a Linux machine?

Alternative, on MacOS I think the best idea would be to use docker and this : https://github.com/PyLops/pylops-docker/tree/master/curvelops_notebook :)

Let us know how it goes

**Comment by Bernalms** [comment]
Hi thanks for your time professor!
Yes i have access to a Linux machine (my personal laptop) so i will try to run all steps there. Thanks for the suggestion of using Docker. Had not thought about it.
As per the issues yes, problems seem to be native to MacOS as the library does not even seem to build properly (no scripts live under the package directory after installation except for build and init).
