### ISSUE TITLE
Managed to install on MacOS 12

### ISSUE THREAD

**Issue by Bernalms** [DIG-Kaust/conda_envs#2]
After some trial and error I was able to install on MacOS 12. one of the key questions i have is: 
One consistent error when installing curvelops was that there is a call inside fdct to _fdct3_wrapper.py BUT the function itself has no initial underscore. Is this because the library did not get properly built or is this a true typo?
My goal would be to put a small video OR latex document summarizing how to install on MacOS.

**Comment by mrava87** [comment]
Thanks, this is great :)

I am not sure about the question, I think this function gets built automatically during the Pybind installation process. I'll make an issue on Curvelops to check with the main developer

**Comment by cako** [comment]
Hi @Bernalms, I'm not sure I'm following the issue. After build, the structure of the library should look something like this:

```bash
curvelops/
    build/
        ...
    cpp/
        fdct2d_wrapper.cpp
        fdct3d_wrapper.cpp
    curvelops/
        __init__.py
        curvelops.py
        fdct2d_wrapper.cpython-310-x86_64-linux-gnu.so
        fdct3d_wrapper.cpython-310-x86_64-linux-gnu.so
```

Inside `curvelops.py`, there are no calls to an _fdct3_wrapper.py. Only to the `.so` files which are imported with:
```python
from .fdct2d_wrapper import *
from .fdct3d_wrapper import *
```

I guess it is possible that `_fdct3_wrapper.py`  is cropping up in the unfinished build, but I didn't find any file like that in the build directory. Could you post a screenshot of where it is appearing?
